services:
  actual-budget:
    build:
      context: ./actual-budget
      dockerfile: sync-server.Dockerfile
    image: actual-budget-custom:v1.0
    container_name: actual-budget
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - actual-data:/data

volumes:
  actual-data:
